---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-kustomize-sed-kustomization
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: kustomize-sed-kustomization/base
    repoURL: https://github.com/abangser/argocd-examples.git
    targetRevision: HEAD
