---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-helm
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: helm/
    repoURL: https://github.com/abangser/argocd-examples.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: commit_sha 
          value: $ARGOCD_APP_REVISION
