version: 2.1

orbs:
  docker: circleci/docker@1.4.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: abangser/argo-nginx-test
      - docker/push:
          digest-path: /tmp/digest.txt
          image: abangser/argo-nginx-test
          tag: $CIRCLE_SHA1

workflows:
  commit:
    jobs:
      - build-and-push