version: 2.1

orbs:
  docker: circleci/docker@1.4.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: abangser/argo-nginx-test
      - docker/push:
          digest-path: /tmp/digest.txt
          image: abangser/argo-nginx-test
          tag: $CIRCLE_SHA1

  GenerateYAML:
    docker:
      - image: cimg/base:2020.06
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run : |
          git clone https://$GITHUB_NAME:$GITHUB_PERSONAL_TOKEN@github.com/abangser/argocd-examples.git /tmp/argocd-examples
          cd /tmp/argocd-examples
          git status
          git log -2
          TAG=$(git rev-parse @~)
          sed -E 's/(argo-nginx-test)(.*)/\1:'$TAG'/' kustomize/base/deployment.yml
          git config credential.helper 'cache --timeout=120'
          git config user.email "CircleCI"
          git config user.name "CircleCI"
          git diff
#          git add .
#          git commit -m "Update via CircleCI"
#          # Push quietly to prevent showing the token in log
#          git push -q https://$GITHUB_NAME:$GITHUB_PERSONAL_TOKEN@github.com/abangser/argocd-examples.git master

workflows:
  commit:
    jobs:
      - build-and-push
      - GenerateYAML