version: 2.1

orbs:
  docker: circleci/docker@1.4.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: abangser/argo-nginx-test
      - docker/push:
          digest-path: /tmp/digest.txt
          image: abangser/argo-nginx-test
          tag: $CIRCLE_SHA1

  sed-patch-both-kustomize-image-tags:
    docker:
      - image: cimg/base:2020.06
    steps:
      - run : |
          git clone https://$GITHUB_NAME:$GITHUB_PERSONAL_TOKEN@github.com/abangser/argocd-examples.git /tmp/argocd-examples
          cd /tmp/argocd-examples
          PREVIOUS_COMMIT_SHA=$(git rev-parse @~)
          PREVIOUS_AUTHOR=$(git log --format='%ae' -1)
          if [ "$PREVIOUS_AUTHOR" = "CircleCI" ]; then
            echo "Git tag is already set to last released change"
            exit 0
          else
            echo "Setting git tag to previous released change"
            ### First patching deployment file (solution 1)
            sed --in-place -E 's/(argo-nginx-test)(.*)/\1:'$PREVIOUS_COMMIT_SHA'/' kustomize-sed-deployment/base/deployment.yml
            ### second patch kustomize override (solution 2) can be done with `kustomize edit set image :534`
            sed --in-place -E 's/(newTag)(.*)/\1: '$PREVIOUS_COMMIT_SHA'/' kustomize-sed/base/kustomization.yml
            git config credential.helper 'cache --timeout=120'
            git config user.email "CircleCI"
            git config user.name "CircleCI"
            git add .
            git commit -m "Update via CircleCI"
            # Push quietly to prevent showing the token in log
            git push -q https://$GITHUB_NAME:$GITHUB_PERSONAL_TOKEN@github.com/abangser/argocd-examples.git master
          fi

workflows:
  commit:
    jobs:
      - build-and-push
      - sed-patch-both-kustomize-image-tags
