version: 2.1

orbs:
  docker: circleci/docker@1.4.0
  buildevents: honeycombio/buildevents@0.2.7

executors:
  go:
    docker:
    - image: circleci/golang:1.12

jobs:
  setup:
    executor: go
    steps:
    - buildevents/start_trace

  watch:
    executor: go
    steps:
    - buildevents/watch_build_and_finish

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: abangser/argo-nginx-test
      - docker/push:
          digest-path: /tmp/digest.txt
          image: abangser/argo-nginx-test
          tag: $CIRCLE_SHA1

  tag-release:
    docker:
      - image: alpine/git
    steps:
      - run:
          name: Tag commit as ready for release
          command: |
            git tag -a production -m "releasing commit $CIRCLE_SHA1"
            git push --tags --force

workflows:
  commit:
    jobs:
      - setup
      - watch:
          requires:
          - setup
      - build-and-push
      - tag-release:
          requires:
            - build-and-push
