apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-kustomize
  labels:
    app: nginx-kustomize
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-kustomize
  template:
    metadata:
      labels:
        app: nginx-kustomize
    spec:
      containers:
        - name: nginx
          image: abangser/argo-nginx-test:56535ce23a9438122e30403c3d197df1e9d3b878
          ports:
            - containerPort: 80